"""add CheckConstraints for ships

Revision ID: 28b81c589a65
Revises: 9a669bb6353a
Create Date: 2026-07-22 18:24:33.232093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b81c589a65'
down_revision: Union[str, Sequence[str], None] = '9a669bb6353a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add check constraints to ensure sensible ship data
    op.create_check_constraint(
        "ck_ship_current_cargo",
        "ships",
        "current_cargo >= 0",
    )

    op.create_check_constraint(
        "ck_ship_cargo_capacity",
        "ships",
        "cargo_capacity >= 0",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_ship_cargo_capacity", "ships", type_="check")
    op.drop_constraint("ck_ship_current_cargo", "ships", type_="check")
    # ### end Alembic commands ###
