"""removed captain_id from ship

Revision ID: 32b5cf6577e2
Revises: 88582088655b
Create Date: 2026-07-17 22:36:24.635841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32b5cf6577e2'
down_revision: Union[str, Sequence[str], None] = '88582088655b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   
    # Remove FK to captains
    op.drop_constraint(
        "ships_captain_id_fkey",
        "ships",
        type_="foreignkey"
    )

    # Remove captain_id column from ships
    op.drop_column(
        "ships",
        "captain_id"
    )

    # Remove captains table
    op.drop_table(
        "captains"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captains_id'), table_name='captains')
    op.create_table('voyage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departure_harbor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destination_harbor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('departure_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('arrival_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estimated_arrival', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('travel_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("'travel_status'::text = ANY (ARRAY['scheduled'::text, 'departed'::text, 'arrived'::text, 'cancelled'::text])", name=op.f('voyage_travel_status')),
    sa.CheckConstraint('departure_harbor_id <> destination_harbor_id', name=op.f('ck_voyage_different_harbors')),
    sa.ForeignKeyConstraint(['departure_harbor_id'], ['harbors.id'], name=op.f('voyage_departure_harbor_id_fkey')),
    sa.ForeignKeyConstraint(['destination_harbor_id'], ['harbors.id'], name=op.f('voyage_destination_harbor_id_fkey')),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], name=op.f('voyage_ship_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('voyage_pkey'))
    )
    # ### end Alembic commands ###
