"""removed captain tabel

Revision ID: 47a723c3899f
Revises: 08d98f49d131
Create Date: 2026-07-17 21:14:44.225452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a723c3899f'
down_revision: Union[str, Sequence[str], None] = '08d98f49d131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
   
    # Remove FK to captains
    op.drop_constraint(
        "ships_captain_id_fkey",
        "ships",
        type_="foreignkey"
    )

    
    # Remove captain_id column from ships
    op.drop_column(
        "ships",
        "captain_id"
    )

    op.drop_index(op.f('ix_captains_id'), table_name='captains')

    # Remove captains table
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('captains',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('experience_years', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_captains_id'), 'captains', ['id'], unique=False)


