"""drop dock_name form docks tabel

Revision ID: 56b4e2d5b108
Revises: f7c7dafcd88f
Create Date: 2026-08-17 18:48:37.595680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b4e2d5b108'
down_revision: Union[str, Sequence[str], None] = 'f7c7dafcd88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docks', 'dock_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docks', sa.Column('dock_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
