"""implemented new  Voyage table

Revision ID: 88582088655b
Revises: 47a723c3899f
Create Date: 2026-07-17 21:44:50.129145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88582088655b'
down_revision: Union[str, Sequence[str], None] = '47a723c3899f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voyage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("departure_harbor_id", sa.Integer(), nullable=False),
        sa.Column("destination_harbor_id", sa.Integer(), nullable=False),
        sa.Column("departure_time", sa.DateTime(), nullable=True),
        sa.Column("ship_id", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(), nullable=True),
        sa.Column("estimated_arrival", sa.DateTime(), nullable=True),
        sa.Column('travel_status', sa.TEXT, nullable= False),
        
        sa.ForeignKeyConstraint(
            ["ship_id"],
            ["ships.id"],
        ),
        sa.ForeignKeyConstraint(
            ["departure_harbor_id"],
            ["harbors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_harbor_id"],
            ["harbors.id"],
        ),
        sa.CheckConstraint("'travel_status' IN ('scheduled','departed','arrived','cancelled')",name="voyage_travel_status"),

        sa.CheckConstraint(
            "departure_harbor_id <> destination_harbor_id",
            name="ck_voyage_different_harbors",
        ),

        sa.PrimaryKeyConstraint("id"),
    )
    
    # ### end Alembic commands ###


def downgrade( ) -> None:
    """Downgrade schema."""
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
