"""changed a ships and docks current_cargo to be 0 by default

Revision ID: 8d278138d56b
Revises: 55e8bb63560e
Create Date: 2026-08-07 19:54:43.352182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d278138d56b'
down_revision: Union[str, Sequence[str], None] = '55e8bb63560e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('ships', 'current_cargo',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    op.alter_column('docks', 'cargo_capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ships', 'current_cargo',
               existing_type=sa.INTEGER(),  
               nullable=False,
               server_default=None)
    op.alter_column('docks', 'cargo_capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default=None)
    # ### end Alembic commands ###
