"""add voyage tabel

Revision ID: 9a669bb6353a
Revises: 5c53be169ebf
Create Date: 2026-07-22 17:02:20.865971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a669bb6353a'
down_revision: Union[str, Sequence[str], None] = '5c53be169ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('travel_status', sa.Enum('scheduled', 'departed', 'arrived', 'cancelled',name='voyage_status'), nullable=True),
    sa.Column('departure_harbor_id', sa.Integer(), nullable=False),
    sa.Column('destination_harbor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departure_harbor_id'], ['harbors.id'], ),
    sa.ForeignKeyConstraint(['destination_harbor_id'], ['harbors.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voyage_id'), 'voyage', ['id'], unique=False)

    op.add_column('harbors', sa.Column('timezone', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('harbors', 'dock_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harbors', sa.Column('dock_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('harbors', 'timezone')
    op.drop_index(op.f('ix_voyage_id'), table_name='voyage')
    op.drop_table('voyage')
    # ### end Alembic commands ###
