"""add ship_class to ships table  and dock_class to docks table

Revision ID: d0e78520728c
Revises: dee3a0431a6e
Create Date: 2026-07-22 19:40:37.065713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e78520728c'
down_revision: Union[str, Sequence[str], None] = 'dee3a0431a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    size_enum = sa.Enum(
        'small',
        'medium',
        'large',
        name='vessel_size_enum'
    )

    size_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('docks',sa.Column('dock_size',size_enum,nullable=True))

    op.add_column('ships',sa.Column('ship_size',size_enum,nullable=True))
    # ### end Alembic commands ###

'Fishing','Cargo','Container','Tanker','Passenger','Tug','Ferry'
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'vessel_size_enum')
    op.drop_column('docks', 'vessel_size_enum')
    # ### end Alembic commands ###
