"""add Checks for dockings and docks

Revision ID: dee3a0431a6e
Revises: 28b81c589a65
Create Date: 2026-07-22 18:48:48.675601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dee3a0431a6e'
down_revision: Union[str, Sequence[str], None] = '28b81c589a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
           "ck_dock_minimum_cargo",
           "docks",
           "cargo_capacity >= 0",
       )
    op.create_check_constraint(
        "ck_departure_after_arrival",
        "dockings",
        'departure_date IS NULL OR departure_date >= arrival_date'
    )

    op.create_check_constraint(
        'ck_arival_order_check',
        'voyage',
        'departure_date >= estimated_arrival'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_dock_minimum_cargo", "docks", type_="check")
    # ### end Alembic commands ###
