"""convert vessel sizes to integer enum values

Revision ID: f7c7dafcd88f
Revises: 8d278138d56b
Create Date: 2026-08-12 21:04:46.257285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7c7dafcd88f'
down_revision: Union[str, Sequence[str], None] = '8d278138d56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docks', 'dock_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.execute("""
        ALTER TABLE docks
        ALTER COLUMN dock_size TYPE INTEGER
        USING CASE dock_size::text
            WHEN 'small' THEN 1
            WHEN 'medium' THEN 2
            WHEN 'large' THEN 3
        END
    """)
    op.execute("""
        ALTER TABLE ships
        ALTER COLUMN ship_size TYPE INTEGER
        USING CASE ship_size::text
            WHEN 'small' THEN 1
            WHEN 'medium' THEN 2
            WHEN 'large' THEN 3
        END
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE ships
        ALTER COLUMN ship_size TYPE vessel_size_enum
        USING CASE ship_size
            WHEN 1 THEN 'small'::vessel_size_enum
            WHEN 2 THEN 'medium'::vessel_size_enum
            WHEN 3 THEN 'large'::vessel_size_enum
        END
    """)

    op.execute("""
        ALTER TABLE docks
        ALTER COLUMN dock_size TYPE vessel_size_enum
        USING CASE dock_size
            WHEN 1 THEN 'small'::vessel_size_enum
            WHEN 2 THEN 'medium'::vessel_size_enum
            WHEN 3 THEN 'large'::vessel_size_enum
        END
    """)

    op.alter_column(
        'docks',
        'dock_name',
        existing_type=sa.VARCHAR(length=100),
        nullable=False
    )
    # ### end Alembic commands ###
